//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceRefParkingSpotBot {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefParkingSpotBot.IBotService")]
    public interface IBotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotsData", ReplyAction="http://tempuri.org/IBotService/GetSpotsDataResponse")]
        BOT_SpotSensor.ParkingSpot[] GetSpotsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotsData", ReplyAction="http://tempuri.org/IBotService/GetSpotsDataResponse")]
        System.Threading.Tasks.Task<BOT_SpotSensor.ParkingSpot[]> GetSpotsDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotData", ReplyAction="http://tempuri.org/IBotService/GetSpotDataResponse")]
        BOT_SpotSensor.ParkingSpot GetSpotData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotData", ReplyAction="http://tempuri.org/IBotService/GetSpotDataResponse")]
        System.Threading.Tasks.Task<BOT_SpotSensor.ParkingSpot> GetSpotDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotString", ReplyAction="http://tempuri.org/IBotService/GetSpotStringResponse")]
        string GetSpotString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotString", ReplyAction="http://tempuri.org/IBotService/GetSpotStringResponse")]
        System.Threading.Tasks.Task<string> GetSpotStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotsString", ReplyAction="http://tempuri.org/IBotService/GetSpotsStringResponse")]
        string GetSpotsString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpotsString", ReplyAction="http://tempuri.org/IBotService/GetSpotsStringResponse")]
        System.Threading.Tasks.Task<string> GetSpotsStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBotServiceChannel : WindowsFormsApp1.ServiceRefParkingSpotBot.IBotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BotServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceRefParkingSpotBot.IBotService>, WindowsFormsApp1.ServiceRefParkingSpotBot.IBotService {
        
        public BotServiceClient() {
        }
        
        public BotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BOT_SpotSensor.ParkingSpot[] GetSpotsData() {
            return base.Channel.GetSpotsData();
        }
        
        public System.Threading.Tasks.Task<BOT_SpotSensor.ParkingSpot[]> GetSpotsDataAsync() {
            return base.Channel.GetSpotsDataAsync();
        }
        
        public BOT_SpotSensor.ParkingSpot GetSpotData() {
            return base.Channel.GetSpotData();
        }
        
        public System.Threading.Tasks.Task<BOT_SpotSensor.ParkingSpot> GetSpotDataAsync() {
            return base.Channel.GetSpotDataAsync();
        }
        
        public string GetSpotString() {
            return base.Channel.GetSpotString();
        }
        
        public System.Threading.Tasks.Task<string> GetSpotStringAsync() {
            return base.Channel.GetSpotStringAsync();
        }
        
        public string GetSpotsString() {
            return base.Channel.GetSpotsString();
        }
        
        public System.Threading.Tasks.Task<string> GetSpotsStringAsync() {
            return base.Channel.GetSpotsStringAsync();
        }
    }
}
