//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.SpotService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParkingSpot", Namespace="http://schemas.datacontract.org/2004/07/BOT_SpotSensor")]
    [System.SerializableAttribute()]
    public partial class ParkingSpot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntegerBatteryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.SpotService.Status StatusStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntegerBatteryStatus {
            get {
                return this.IntegerBatteryStatusField;
            }
            set {
                if ((this.IntegerBatteryStatusField.Equals(value) != true)) {
                    this.IntegerBatteryStatusField = value;
                    this.RaisePropertyChanged("IntegerBatteryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.SpotService.Status StatusStatus {
            get {
                return this.StatusStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusStatusField, value) != true)) {
                    this.StatusStatusField = value;
                    this.RaisePropertyChanged("StatusStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringId {
            get {
                return this.StringIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StringIdField, value) != true)) {
                    this.StringIdField = value;
                    this.RaisePropertyChanged("StringId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringLocation {
            get {
                return this.StringLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StringLocationField, value) != true)) {
                    this.StringLocationField = value;
                    this.RaisePropertyChanged("StringLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringName {
            get {
                return this.StringNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StringNameField, value) != true)) {
                    this.StringNameField = value;
                    this.RaisePropertyChanged("StringName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringType {
            get {
                return this.StringTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StringTypeField, value) != true)) {
                    this.StringTypeField = value;
                    this.RaisePropertyChanged("StringType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/BOT_SpotSensor")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpotService.IBotService")]
    public interface IBotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpots", ReplyAction="http://tempuri.org/IBotService/GetSpotsResponse")]
        WindowsFormsApp1.SpotService.ParkingSpot[] GetSpots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotService/GetSpots", ReplyAction="http://tempuri.org/IBotService/GetSpotsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.SpotService.ParkingSpot[]> GetSpotsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBotServiceChannel : WindowsFormsApp1.SpotService.IBotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BotServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.SpotService.IBotService>, WindowsFormsApp1.SpotService.IBotService {
        
        public BotServiceClient() {
        }
        
        public BotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.SpotService.ParkingSpot[] GetSpots() {
            return base.Channel.GetSpots();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.SpotService.ParkingSpot[]> GetSpotsAsync() {
            return base.Channel.GetSpotsAsync();
        }
    }
}
